language: python

python:
    - "3.3"
    - "3.4"

sudo: false

env:
    - MYSQL_USER=travis MYSQL_HOST=127.0.0.1 POSTGRESQL_USER=postgres POSTGRESQL_HOST=127.0.0.1

services:
    - mongodb

before_install:
    - bash bin/check_signoff.sh
    - pip install -q flake8
    - flake8

install:
    - bash tests/start-neo4j.sh
    - pip install -r tests/requirements.txt

before_script:
    - mysql -u $MYSQL_USER < tests/input/chinook_mysql.sql > /dev/null
    - psql -U $POSTGRESQL_USER -c 'create database chinook' > /dev/null
    - psql -U $POSTGRESQL_USER -d chinook < tests/input/chinook_postgresql.sql > /dev/null
    - mongorestore --db chinook tests/input/mongodb > /dev/null

script:
    - coverage run test_suite.py

after_success:
    - pip install -q coveralls
    - coveralls > /dev/null
